### ISSUE TITLE
Compatibility with VS 2012

### ISSUE THREAD

**Issue by takwirira** [bbarnhill/barcodelib#18]
Hi, I have VS 2012 Express for Windows Applications but when I try and open the project it says it's not compatible. Do you have a new version of the files please?

**Comment by bbarnhill** [comment]
This was created with VS2012 ... I dont know what you mean by a newer copy of the project files.  The only file that changes between VS2008 and VS2012 was the solution file if Im not mistaken.

**Comment by takwirira** [comment]
That's fine I managed to get to to work. Thanks so much

**Comment by bbarnhill** [comment]
Glad you got it working.  Shouldnt have been too hard even if you needed to manually modify the sln file.  Hope you find it useful!!

**Comment by binki** [comment]
@takwirira I recommend switching to VS Community Edition and updating to the latest release (2015) if possible. Staying outdated only causes pain ;-).

**Comment by bbarnhill** [comment]
will look into this
