### ISSUE TITLE
Create or link to official nuget package distribution from this project

### ISSUE THREAD

**Issue by binki** [bbarnhill/barcodelib#3]
For many cases where barcodelib works as-is for developers, it would be great if it could be imported to a project via nuget. Providing it as-is encourages developers to copy/paste/maintain code that is not their own into their projects, which basically has the problems that come with bundling or statically linking against libraries.

So, if you could yourself provide a nuget package, endorse an existing one (if there is any), or would be willing to endorse a nuget package that a community member might make in the future, that’d be great.

Thanks!

**Comment by bbarnhill** [comment]
this project is open source so if you want to create a pull request or help provide a nuget package that would be great.  Im all about supporting the community however we can.

**Comment by binki** [comment]
(The pull request for this is #4).

**Comment by binki** [comment]
Thanks for uploading the nuget package!

**Comment by bbarnhill** [comment]
you are welcome ... thanks for contributing!!!
