### ISSUE TITLE
Add dynamic sizing Width/Height calculation feature

### ISSUE THREAD

**Issue by binki** [bbarnhill/barcodelib#5]
In looking at the old barcodelib embedded in our unshareable project code, it looks like we rely on the the old image sizing behavior documented in the ChangeLog at [codeproject](http://www.codeproject.com/Articles/20823/Barcode-Image-Generation-Library):

> December 3, 2008
> 
> * Can now specify image size before encoding.
> 
> * Complete overhaul of the drawing function to allow for dynamic drawing size. Now calculates the bar width based on the specified image size. Removed resize functions due to inaccuracy of the resizing method. The encoding functions have been revamped to reflect these changes (removed some of the overloaded functions referencing the resize functions). Also removed a majority of the case statements from Generate_Image() to simplify it. Updated the article to reflect the changes to the Encode functions and the changes to the drawing functions.

There are a few things about how it looks that the current API works that are not nice here. First, to generate a barcode for an arbitrary string, the library’s user must be able to somehow predict the number of pixels necessary to render that barcode. This is really the biggest issue for me. I would like to be able to render a string and let the library automatically set `BarcodeLib.Barcode.Width` to a high-enough value for me instead of getting an exception “EGENERATE_IMAGE-2: Image size specified not large enough to draw image. (Bar size determined to be less than 1 pixel)”.

To remedy this, I would like it to be possible to opt into the old behavior with an API like this:

    /// <summary>If non-null, sets the width of a bar. <see cref="Width"/> is ignored and calculated automatically.</summary>
    public int? BarWidth { get; set; }
    
    /// <summary>If non-null, <see cref="Height"/> is ignored and set to <see cref="Width"/> divided by this value rounded down.</summary>
    /// <remarks><para>As longer barcodes may be more difficult to align a scanner gun with,
    /// growing the height based on the width automatically allows the gun to be rotated the
    /// same amount regardless of how wide the barcode is. A recommended value is 2.
    /// </para></remarks>
    public double? AspectRatio { get; set; }

The idea is that you could choose to dynamically calculate the `Width`, `Height`, both, or neither. (Though “dynamically” calculating the `Height` would basically be statically calculating it in the end ;-)). Does this API sound good? I think I’ll start working on a pull request, but thought I’d put this out here in case I get lost in some rabbit hole or others have comments/suggestions on this approach.

**Comment by bbarnhill** [comment]
very good write up ... let me ponder this for a bit and read it again when I get home.  THIS is what this project was open sourced for.  Improvements and expansion of the original idea.  Finally someone that understands it and doesnt berate me on the coding. :) (yes I have a person that is berating me on the coding and pretty relentlessly I might add)

**Comment by bbarnhill** [comment]
sounds good.  If you want to put a pull request together Ill anxiously await it so I can review it!!!  Thanks for the interest and I hope more people find this useful and worth contributing to.

**Comment by binki** [comment]
pull is #6.

**Comment by bbarnhill** [comment]
since we pulled that other code in are you ok with closing this issue?
